### GET alle tickets
GET http://localhost:5204/api/tickets

### GET Admin overzicht tickets (Admin)
GET http://localhost:5204/api/tickets?userRole=admin

### GET Overzicht van eigen tickets (User)
GET http://localhost:5204/api/tickets?userRole=user&userId=1

### GET overzicht alle gebruikers (Admin)
GET http://localhost:5204/api/users?userRole=admin

### POST registreer nieuwe gerbuiker
POST http://localhost:5204/api/users/register
Content-Type: application/json

{
  "username": "DaanTest123",
  "password": "testtest123",
  "role": "user"
}

### POST nieuw ticket
POST http://localhost:5204/api/tickets
Content-Type: application/json

{
  "title": "Test Ticket",
  "description": "Eerste ticket via VSCode",
  "status": "Open",
  "priority": "Low",
  "createdBy": 1,
  "assignedTo": null
}

### PUT ticket bijwerken 
PUT http://localhost:5204/api/tickets/7
Content-Type: application/json

{
  "ticketID": 7,
  "title": "Aangepast ticket",
  "description": "Nu met update",
  "status": "InProgress",
  "priority": "Medium",
  "assignedTo": null,
  "createdBy": 1
}

### PUT ticket prioriteit aanpassen (Admim)
PUT http://localhost:5204/api/tickets/5/priority?userRole=admin
Content-Type: application/json

"High"

### PUT ticket Toewijzen (Admin)
PUT http://localhost:5204/api/tickets/5/assign/3?userRole=admin

### DELETE ticket
DELETE http://localhost:5204/api/tickets/7?isAdmin=true

### Create Admin User (secure)
POST http://localhost:5204/api/users/create-admin?key=BeveiligingAdminAccountTest123
Content-Type: application/json

{
  "username": "DaanAdmin",
  "password": "AdminAccountDaanTest123",
  "role": "admin"
}
